###
##### PRODUTO #####
###
GET http://localhost:8080/produto/ HTTP/1.1


###

POST http://localhost:8080/produto/incluir HTTP/1.1
content-type: application/json

{
    "nome":"Batata",
    "preco": "40.00",
    "descricao":"Batata Rosti de Calabresa",
    "situacao":"disponivel",
    "imagem":"123"
}

###
##### CLIENTE #####
###
GET http://localhost:8080/cliente/ HTTP/1.1


###

POST http://localhost:8080/cliente/incluir HTTP/1.1
content-type: application/json

{
    "nome": "Godofredo",
    "cpf": "158467984-03",
    "telefone": "2298231-4021",
    "logradouro":"Rua PdP",
    "numero": "4",
    "nomeBairro": "Praia do Pecado"
}

###

GET http://localhost:8080/cliente/alterar145864324-26 HTTP/1.1
content-type: application/json

{
    "nome": "Lucia",
    "telefone": "22982448974"
}

###

GET http://localhost:8080/cliente/excluir145864324-26 HTTP/1.1

###
##### ENDERECO #####
###

GET http://localhost:8080/endereco/ HTTP/1.1


###

POST http://localhost:8080/endereco/incluir HTTP/1.1
content-type: application/json

{
    "logradouro":"Rua M",
    "numero": "100",
    "nomeBairro": "Mirante"
}

###

GET http://localhost:8080/endereco/alterar13 HTTP/1.1
content-type: application/json

{
    "logradouro":"Rua M",
    "numero": "1"
}

###

GET http://localhost:8080/endereco/excluir2 HTTP/1.1

###
##### BAIRRO #####
###
GET http://localhost:8080/bairro/ HTTP/1.1


###

POST http://localhost:8080/bairro/incluir HTTP/1.1
content-type: application/json

{
    "nomeBairro": "Mirante",
    "valor": "0"
}

###

GET http://localhost:8080/bairro/alterar4 HTTP/1.1
content-type: application/json

{
    "nomeBairro": "Mirante",
    "valor": "0"
}

###

GET http://localhost:8080/bairro/excluir1 HTTP/1.1